const SVIDEO_SOURCE = 0x04
const COMPONENT = 0x08
const AV_SOURCE = 0x0C
const AV2_SOURCE = 0x0D
const EXT_SOURCE = 0x0E
const PC_SOURCE = 0x14
const DVI_SOURCE = 0x18
const BNC_SOURCE = 0x1E
const DVIVIDEO_SOURCE = 0x1F
const MAGICINFO_SOURCE = 0x20
const HDMI1_SOURCE = 0x21
const HDMI1PC_SOURCE = 0x22
const HDMI2_SOURCE = 0x23
const HDMI2PC_SOURCE = 0x24
const DISPLAYPORT_SOURCE = 0x25
const DISPLAYPORT2_SOURCE = 0x26
const DISPLAYPORT3_SOURCE = 0x27
const RF_SOURCE = 0x30
const HDMI3_SOURCE = 0x31
const HDMI3PC_SOURCE = 0x32
const HDMI4_SOURCE = 0x33
const HDMI4PC_SOURCE = 0x34
const DTV_SOURCE = 0x40
const PLUGIN_MODULE_SOURCE = 0x50
const HDBT_SOURCE = 0x55
const MEDIA_SOURCE = 0x60
const WIDI_SOURCE = 0x61
const INTERNAL_USB_SOURCE = 0x62
const URL_SOURCE = 0x63
const IWB_SOURCE = 0x64
const WEB_SOURCE = 0x65

const INPUT_SOURCES = {
  "PC": PC_SOURCE,
  "BNC": BNC_SOURCE,
  "DVI": DVI_SOURCE,
  "A/V": AV_SOURCE,
  "A/V 2": AV2_SOURCE,
  "Ext": EXT_SOURCE,
  "S-Video": SVIDEO_SOURCE,
  "Component": COMPONENT,
  "Magicinfo": MAGICINFO_SOURCE,
  "DVI-V": DVIVIDEO_SOURCE,
  "TV": RF_SOURCE,
  "DTV": DTV_SOURCE,
  "HDMI1": HDMI1_SOURCE,
  "HDMI1-PC": HDMI1PC_SOURCE,
  "HDMI2": HDMI2_SOURCE,
  "HDMI2-PC": HDMI2PC_SOURCE,
  "HDMI3": HDMI3_SOURCE,
  "HDMI3-PC": HDMI3PC_SOURCE,
  "HDMI4": HDMI4_SOURCE,
  "HDMI4-PC": HDMI4PC_SOURCE,
  "DisplayPort": DISPLAYPORT_SOURCE,
  "DisplayPort2": DISPLAYPORT2_SOURCE,
  "DisplayPort3": DISPLAYPORT3_SOURCE,
  "Plug-In Module": PLUGIN_MODULE_SOURCE,
  "HDBT": HDBT_SOURCE,
  "Media": MEDIA_SOURCE,
  "WiDi": WIDI_SOURCE,
  "Internal/USB": INTERNAL_USB_SOURCE,
  "URL Launcher": URL_SOURCE,
  "IWB": IWB_SOURCE,
  "Web Browser": WEB_SOURCE
}

module.exports = {
  PC_SOURCE,
  BNC_SOURCE,
  DVI_SOURCE,
  AV_SOURCE,
  AV2_SOURCE,
  EXT_SOURCE,
  SVIDEO_SOURCE,
  COMPONENT,
  MAGICINFO_SOURCE,
  DVIVIDEO_SOURCE,
  RF_SOURCE,
  DTV_SOURCE,
  HDMI1_SOURCE,
  HDMI1PC_SOURCE,
  HDMI2_SOURCE,
  HDMI2PC_SOURCE,
  HDMI3_SOURCE,
  HDMI3PC_SOURCE,
  HDMI4_SOURCE,
  HDMI4PC_SOURCE,
  DISPLAYPORT_SOURCE,
  DISPLAYPORT2_SOURCE,
  DISPLAYPORT3_SOURCE,
  PLUGIN_MODULE_SOURCE,
  MEDIA_SOURCE,
  WIDI_SOURCE,
  INTERNAL_USB_SOURCE,
  URL_SOURCE,
  IWB_SOURCE,
  WEB_SOURCE,

  INPUT_SOURCES
}